def getMenuQuery():
    sql = " SELECT p.page_id, p.page_flag, p.page_key, p.page_order, p.page_auth::jsonb, l.object_label::jsonb->>:language AS page_name, json_agg(row_to_json(items)) AS items "
    sql += " FROM mente.page_info p "
    sql += " LEFT JOIN mente.label_info l ON l.properties_name=p.page_id::varchar "
    sql += " LEFT JOIN (SELECT pr.page_group_id, p1.page_id, p1.page_flag, p1.page_key, p1.page_order, p1.page_auth::jsonb, l1.object_label::jsonb->>:language AS page_name "
    sql += " FROM mente.page_info p1 "
    sql += " LEFT JOIN mente.label_info l1 ON l1.properties_name=p1.page_id::varchar  "
    sql += " LEFT JOIN mente.page_group_rel pr ON pr.page_id=p1.page_id "
    sql += " WHERE p1.company_id=:cId AND p1.page_deleted=0 AND p1.page_key<>'mente.page_info') AS items ON items.page_group_id=p.page_id "
    sql += " WHERE p.company_id=:cId AND p.page_deleted=0 AND p.page_key<>'mente.page_info' "
    sql += " AND p.page_id NOT IN(SELECT page_id FROM mente.page_group_rel) "
    sql += " GROUP BY p.page_id, p.page_key, l.object_label ORDER BY p.page_order, p.page_id "
    return sql

def getPageFields():
    sql = " SELECT p.page_id, p.page_key, p.page_auth::jsonb, l.object_label::jsonb->>:language AS page_name "
    sql += " ,json_agg( "
    sql += " json_build_object( "
    sql += " 'form_id', f.form_id, "
    sql += " 'className', f.class_name, "
    sql += " 'object_key', f.object_key, "
    sql += " 'object_type', f.object_type, "
    sql += " 'idx', f.idx, "
    sql += " 'object', (SELECT json_agg( "
    sql += " json_build_object( "
    sql += " 'schema', json_build_object( "
    sql += " 'schema_id', s.schema_id, "
    sql += " 'schema_type', s.schema_type, "
    sql += " 'schema_key', s.schema_key, "
    sql += " 'title', pll.object_label::jsonb->>:language, "
    sql += " 'type', s.object_type, "
    sql += " 'form_idx', f.idx, "
    sql += " 'idx', s.idx, "
    sql += " 'properties', COALESCE((SELECT json_object_agg(pp.properties_name, pp.value::jsonb || json_build_object('title', pl.object_label::jsonb->>:language)::jsonb) FROM mente.properties_info pp LEFT JOIN mente.label_info pl ON pl.properties_name=pp.properties_name WHERE pp.schema_id=s.schema_id)::jsonb, '{}'::jsonb) "
    sql += " ) "
    sql += " ,'ui', COALESCE((SELECT json_object_agg(u.properties_name, u.value) FROM mente.ui_info u WHERE u.schema_id=s.schema_id)::jsonb, '{}'::jsonb) "
    sql += " ,'data', COALESCE((SELECT json_object_agg(d.properties_name, d.value) FROM mente.default_data_info d WHERE d.schema_id=s.schema_id)::jsonb, '{}'::jsonb) "
    sql += " )) FROM mente.schema_info s "
    sql += " LEFT JOIN mente.label_info pll ON pll.properties_name=s.schema_key "
    sql += " WHERE s.form_id=f.form_id)) "
    sql += " ) AS form "
    sql += " FROM mente.page_info p "
    sql += " LEFT JOIN mente.form_info f ON f.page_id=p.page_id "
    sql += " LEFT JOIN mente.label_info l ON l.properties_name=p.page_id::varchar "
    sql += " WHERE p.company_id=:cId AND p.page_deleted=0 AND p.page_id=:pId "
    sql += " GROUP BY p.page_id, p.page_key, p.page_auth::jsonb, l.object_label "
    return sql

# def getPageFields():
#     sql = " SELECT p.page_id, p.page_key, p.company_id, p.page_auth::jsonb, l.object_label::jsonb->>'ja' AS page_name, json_agg(f) AS form "
#     sql += " FROM (SELECT "
#     sql += " s.page_id "
#     sql += " ,s.object_type "
#     sql += " ,s.object_key "
#     sql += ' ,s.class_name AS "className" '
#     sql += " ,s.idx "
#     sql += " ,CASE WHEN s.object_type = 'div' THEN "
#     sql += " json_build_object( "
#     sql += " 'schema_id', s.schema_id "
#     sql += " ,'schema', (s.value::jsonb || json_build_object('properties', COALESCE((SELECT json_object_agg(pp.properties_name, pp.value) FROM mente.properties_info pp WHERE pp.schema_id=s.schema_id)::jsonb, '{}'::jsonb))::jsonb) "
#     sql += " ,'ui', COALESCE((SELECT json_object_agg(u.properties_name, u.value) FROM mente.ui_info u WHERE u.schema_id=s.schema_id)::jsonb, '{}'::jsonb) "
#     sql += " ,'data', COALESCE((SELECT json_object_agg(d.properties_name, d.value) FROM mente.default_data_info d WHERE d.schema_id=s.schema_id)::jsonb, '{}'::jsonb) "
#     sql += " ) ELSE "
#     sql += " json_agg(json_build_object( "
#     sql += " 'schema_id', s.schema_id "
#     sql += " ,'schema', (s.value::jsonb || json_build_object('properties', COALESCE((SELECT json_object_agg(pp.properties_name, pp.value) FROM mente.properties_info pp WHERE pp.schema_id=s.schema_id)::jsonb, '{}'::jsonb))::jsonb) "
#     sql += " ,'ui', COALESCE((SELECT json_object_agg(u.properties_name, u.value) FROM mente.ui_info u WHERE u.schema_id=s.schema_id)::jsonb, '{}'::jsonb) "
#     sql += " ,'data', COALESCE((SELECT json_object_agg(d.properties_name, d.value) FROM mente.default_data_info d WHERE d.schema_id=s.schema_id)::jsonb, '{}'::jsonb) "
#     sql += " )) "
#     sql += " END AS object "
#     sql += " FROM mente.schema_info s "
#     sql += " LEFT JOIN mente.properties_info pp ON pp.schema_id=s.schema_id "
#     sql += " GROUP BY s.page_id, s.schema_id, s.object_type, s.object_key, s.class_name, s.idx "
#     sql += " ) AS f "
#     sql += " INNER JOIN mente.page_info p ON p.page_id=f.page_id "
#     sql += " INNER JOIN mente.object_label_info l ON l.object_id=p.page_id AND l.object_type=1 "
#     sql += " WHERE p.company_id=:cId AND p.page_id=:pId AND p.page_deleted=0 "
#     sql += " GROUP BY p.page_id, p.page_key, p.company_id, p.page_auth, l.object_label "
#     return sql