def getColums():
    sql = " SELECT p.page_id, p.page_key, p.page_auth::jsonb, l.object_label::jsonb->>:language AS page_name, json_agg(f.fields) AS items FROM ( "
    sql += " SELECT f.page_id, "
    sql += " json_build_object( "
    sql += " 'field', p.properties_name, "
    sql += " 'view', p.value::jsonb->'auth'->'view', "
    sql += " 'label', pl.object_label::jsonb->>:language, "
    sql += " 'type', substring(p.properties_name, 0, position('_' IN p.properties_name)) "
    sql += " ) AS fields "
    sql += " FROM mente.form_info f "
    sql += " LEFT JOIN mente.schema_info s ON f.form_id=s.form_id "
    sql += " LEFT JOIN mente.properties_info p ON p.schema_id=s.schema_id "
    sql += " INNER JOIN mente.label_info pl ON pl.properties_name=p.properties_name "
    sql += " ) AS f "
    sql += " INNER JOIN mente.page_info p ON p.page_id=f.page_id "
    sql += " LEFT JOIN mente.label_info l ON l.properties_name=p.page_id::varchar "
    sql += " WHERE p.company_id=:cId AND p.page_deleted=0 AND p.page_id=:pId "
    sql += " GROUP BY p.page_id, l.object_label "
    return sql